# Generated by Django 3.0.5 on 2021-05-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live')], default='Upcoming', max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
