# Generated by Django 3.0.5 on 2021-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210505_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='que_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Quiz/'),
        ),
    ]
